### ISSUE TITLE
Add new items to the to-do list

### ISSUE THREAD

**Issue by BubbleNeumann** [BubbleNeumann/webTodo#2]
Add some js logic, which 
- [x] reacts on button pressing and shows the "input" field
- [x] remembers the input

**Comment by BubbleNeumann** [comment]
- [ ] focus on input field
- [ ] mark todos as done

**Comment by BubbleNeumann** [comment]
fully resolved with the last commit
